### PR TITLE
Added Admission and common services

### PR DESCRIPTION
**Pull request by AladdinTheAmplifier**
Adding the services
-> parent Service
-> Admission Registry Service
-> Common Lib Service

### CODE REVIEW

**Review by AladdinTheAmplifier — COMMENTED** [review]
Okay

**Comment by AladdinTheAmplifier** [comment]
Adding the services

**Review by kiranv04 — COMMENTED** [review]
OK

**Review by kiranv04 — COMMENTED** [review]
OK

**Comment by AladdinTheAmplifier** [comment]
Okay

**Pull request merged**
